### PR TITLE
Support empty and binary files

### PR DESCRIPTION
**Pull request by unbrice**

### CODE REVIEW

**Comment by EvanPurkhiser** [comment]
Merging the first one atm, looking a little bit closer at the other :+1:

**Comment by EvanPurkhiser** [comment]
Support for binary files quite possibly broke due to https://github.com/EvanPurkhiser/dots/commit/d25236998aa609d1aa0586ffe2d5208747cc318b.

I'm tinkering with this now as it doesn't seem to have fixed everything exactly right.

**Comment by unbrice** [comment]
Thank you :smile: ! Support for binary file in Python 2 may be broken due to d252369 , but in Python 3 passing through binary files requires using the byte type rather than string and opening files in "b" mode.

**Comment by EvanPurkhiser** [comment]
Thanks again for this PR @unbrice! I've made some implementation modifications to your second commit as f08e714dac0e07e2c3407adac4cf15d42753cf36.

**Comment by unbrice** [comment]
Thanks, it's great that you fixed this!

**Pull request closed without merging**
