### PR TITLE
Added 'groups add/del' functionality and added a --reinstall option. resolves #7

### LINKED ISSUE #7: Force re-running of installation scripts
A '--force' flag for install, or something similar, that forces dots to rerun all installation scripts (*.install files).

At the moment, dots only will execute an installation script if the corresponding configuration file has changed.

### PR DESCRIPTION
**Pull request by countsudoku**
If added two new parameter to the _groups_ command. _add_, which adds groups to the current used groups and _del_, which removes groups from the current used groups. 
So you don't have to use _groups set_ with every current groups and the new group. Now you can use _groups add_ to add one or more groups or _group del_ to remove one or more groups from/to the existing groups.

I've also implemented the --reinstall option with abrevation -r. This resolves #7

### CODE REVIEW

**Comment by countsudoku** [comment]
I've merged the recent changes from other pull requests and some other changes into my branch. So that this is mergable again.

**Comment by countsudoku** [comment]
I've merged the recent changes from other pull requests and some other changes into my branch. So that this is mergable again.

**Comment by countsudoku** [comment]
@EvanPurkhiser  is there any chance, that this gets merged?

**Comment by EvanPurkhiser** [comment]
Hi @countsudoku 

I'm actually working on a golang rewrite of dots on the [go-rewrite](https://github.com/EvanPurkhiser/dots/tree/go-rewrite) branch. It's still somewhat early, but I do plan to support the reinstall feature. However, I likely won't support adding or removing groups, since order is important when specifying a group list.

See GH-20 for my upcoming ideas.

**Pull request closed without merging**
